# Site settings
title: Portfolio of Viktor Henriksson
logo: /CVpicsquare.jpg?raw=true
description: >
  Analyst with experience in financial crime prevention and criminology, passionate to delve into data analytics with a social scientific perspective.
  <br><br>
  <a href="www.linkedin.com/in/viktor-henriksson">My LinkedIn profile</a>

# Build settings
theme: jekyll-theme-minimal
