# Site settings
title: Portfolio of Viktor Henriksson
logo: /CVpicsquare.jpg?raw=true
author:
  name: Viktor Henriksson
  email: viktorhenriksson@msn.com
description: >
  Analyst with experience in financial crime prevention and criminology, passionate to delve into data analytics with a social scientific perspective.

# Build settings
remote_theme: jekyll/minimal
